### ISSUE TITLE
sorry, but how to use it anymore

### ISSUE THREAD

**Issue by intetnet** [alts/fxg2svg#1]
I am not much familiar with python2

**Comment by alts** [comment]
To be totally honest, this was never finished. I went back and tried it with a couple fxg files I had on hand, and in the code's current state, you'll need to do a couple things.

First, copy the fxg file you want to transform, and paste it into the directory with fxg2svg
`mv intetnet_file.fxg fxg2svg/example.fxg`

Then you'll just run the script in that directory, saving the output to some .svg file
`python fxg2svg.py > new_file.svg`

You should hopefully have a non-broken svg file at that location afterward.

**Comment by intetnet** [comment]
ok, I will try it later.

Thank you.
